server {
  listen 8080;
  root /usr/share/nginx/html;

  location ~ \.wasm$ {
    default_type application/wasm;
  }

  location = /lemmings {
    try_files /lemmings.html =404;
  }

  location /lemmings/ {
    try_files $uri /lemmings.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
